server:
  port: 8888

spring:
  application:
    name: spring-cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FrancescaPascalau/config-repo.git
          search-paths: '{application}/{profile}'

encrypt:
#  key: myencryptkey
#  encrypted-prop: "{cipher}689fcbb3fcca766d91ec197de2a3612ede07a6bb3d85855e2b787fac64f5735c"
  key-store:
    password: password