server:
  port: 8888

spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FrancescaPascalau/spring-cloud-server.git
          clone-on-start: true
        bootstrap: true
  security:
    user:
      name: user
      password: password
