server:
  port: 8888

spring:
  application:
    name: spring-cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FrancescaPascalau/config-repo.git
          search-paths: '{application}/{profile}'