server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:FrancescaPascalau/spring-cloud-server.git
          clone-on-start: true
        bootstrap: true
      profile: composite
  security:
    user:
      name: user
      password: password
